version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    machine:
      node:
        version: 0.10.43
    dependencies:
      override:
        - curl https://install.meteor.com | /bin/sh
        - npm install

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
